apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-backend-deployment
  namespace: chatapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-backend
  template:
    metadata:
      labels:
        app: chatapp-backend
    spec:
      containers:
      - name: chatapp-backend-container
        image: aamir977/chatapp-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: MONGODB_URI
          value: "mongodb://root:admin@mongodb:27017/chatApp?authSource=admin"
        - name: PORT
          value: "5001"
        - name: NODE_ENV
          value: "production"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt-secret
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"