apiVersion: v1
kind: Service
metadata:
  name: chatapp-frontend-service
  namespace: chatapp-namespace
spec:
  selector:
    app: chatapp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
