apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: chatapp-service
spec:
  selector:
    app: chatapp-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP