apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatapp-mongo-pvc
  namespace: chatapp-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard